"""
A GraphQL Schema defines the capabilities of a GraphQL server. It exposes all available types and directives on the server, as well as the entry points for query, mutation, and subscription operations.
"""
type __Schema {
  description: String

  """
  A list of all types supported by this server.
  """
  types: [__Type!]!

  """
  The type that query operations will be rooted at.
  """
  queryType: __Type!

  """
  If this server supports mutation, the type that mutation operations will be rooted at.
  """
  mutationType: __Type

  """
  If this server support subscription, the type that subscription operations will be rooted at.
  """
  subscriptionType: __Type

  """
  A list of all directives supported by this server.
  """
  directives: [__Directive!]!
}

"""
The fundamental unit of any GraphQL Schema is the type. There are many kinds of types in GraphQL as represented by the `__TypeKind` enum.

Depending on the kind of a type, certain fields describe information about that type. Scalar types provide no information beyond a name, description and optional `specifiedByURL`, while Enum types provide their values. Object and Interface types provide the fields they describe. Abstract types, Union and Interface, provide the Object types possible at runtime. List and NonNull types compose other types.
"""
type __Type {
  kind: __TypeKind!

  name: String

  description: String

  fields(includeDeprecated: Boolean = false): [__Field!]

  interfaces: [__Type!]

  possibleTypes: [__Type!]

  enumValues(includeDeprecated: Boolean = false): [__EnumValue!]

  inputFields(includeDeprecated: Boolean = false): [__InputValue!]

  ofType: __Type

  specifiedByURL: String
}

"""
An enum describing what kind of type a given `__Type` is.
"""
enum __TypeKind {
  """
  Indicates this type is a scalar.
  """
  SCALAR

  """
  Indicates this type is an object. `fields` and `interfaces` are valid fields.
  """
  OBJECT

  """
  Indicates this type is an interface. `fields`, `interfaces`, and `possibleTypes` are valid fields.
  """
  INTERFACE

  """
  Indicates this type is a union. `possibleTypes` is a valid field.
  """
  UNION

  """
  Indicates this type is an enum. `enumValues` is a valid field.
  """
  ENUM

  """
  Indicates this type is an input object. `inputFields` is a valid field.
  """
  INPUT_OBJECT

  """
  Indicates this type is a list. `ofType` is a valid field.
  """
  LIST

  """
  Indicates this type is a non-null. `ofType` is a valid field.
  """
  NON_NULL
}

"""
Object and Interface types are described by a list of Fields, each of which has a name, potentially a list of arguments, and a return type.
"""
type __Field {
  name: String!

  description: String

  args(includeDeprecated: Boolean = false): [__InputValue!]!

  type: __Type!

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
Arguments provided to Fields or Directives and the input fields of an InputObject are represented as Input Values which describe their type and optionally a default value.
"""
type __InputValue {
  name: String!

  description: String

  type: __Type!

  """
  A GraphQL-formatted string representing the default value for this input value.
  """
  defaultValue: String

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
One possible value for a given Enum. Enum values are unique values, not a placeholder for a string or numeric value. However an Enum value is returned in a JSON response as a string.
"""
type __EnumValue {
  name: String!

  description: String

  isDeprecated: Boolean!

  deprecationReason: String
}

"""
A Directive provides a way to describe alternate runtime execution and type validation behavior in a GraphQL document.

In some cases, you need to provide options to alter GraphQL's execution behavior in ways field arguments will not suffice, such as conditionally including or skipping a field. Directives provide this by describing additional information to the executor.
"""
type __Directive {
  name: String!

  description: String

  locations: [__DirectiveLocation!]!

  args(includeDeprecated: Boolean = false): [__InputValue!]!

  isRepeatable: Boolean!
}

"""
A Directive can be adjacent to many parts of the GraphQL language, a __DirectiveLocation describes one such possible adjacencies.
"""
enum __DirectiveLocation {
  """
  Location adjacent to a query operation.
  """
  QUERY

  """
  Location adjacent to a mutation operation.
  """
  MUTATION

  """
  Location adjacent to a subscription operation.
  """
  SUBSCRIPTION

  """
  Location adjacent to a field.
  """
  FIELD

  """
  Location adjacent to a fragment definition.
  """
  FRAGMENT_DEFINITION

  """
  Location adjacent to a fragment spread.
  """
  FRAGMENT_SPREAD

  """
  Location adjacent to an inline fragment.
  """
  INLINE_FRAGMENT

  """
  Location adjacent to a variable definition.
  """
  VARIABLE_DEFINITION

  """
  Location adjacent to a schema definition.
  """
  SCHEMA

  """
  Location adjacent to a scalar definition.
  """
  SCALAR

  """
  Location adjacent to an object type definition.
  """
  OBJECT

  """
  Location adjacent to a field definition.
  """
  FIELD_DEFINITION

  """
  Location adjacent to an argument definition.
  """
  ARGUMENT_DEFINITION

  """
  Location adjacent to an interface definition.
  """
  INTERFACE

  """
  Location adjacent to a union definition.
  """
  UNION

  """
  Location adjacent to an enum definition.
  """
  ENUM

  """
  Location adjacent to an enum value definition.
  """
  ENUM_VALUE

  """
  Location adjacent to an input object type definition.
  """
  INPUT_OBJECT

  """
  Location adjacent to an input object field definition.
  """
  INPUT_FIELD_DEFINITION
}

"""
An user's saved cart session. Only one cart can be active at a time
"""
type Cart {
  """
  Each user can only have one cart so the ID is the same as the user ID
  """
  userId: ID!

  """
  Items saved in the cart session
  """
  items: [Variant]

  """
  The current total of all the items in the cart, before taxes and shipping
  """
  subtotal: Float
}

type CartMutations {
  checkout(paymentMethodId: ID!): CheckoutResult

  addVariantToCart(variantId: ID!, quantity: Int = 1): ResultWithMessage

  removeVariantFromCart(variantId: ID!, quantity: Int = 1): ResultWithMessage
}

type CheckoutResult {
  successful: Boolean

  orderID: ID
}

"""
Inventory details about a specific Variant
"""
type Inventory {
  """
  Returns true if the inventory count is greater than 0
  """
  inStock: Boolean!

  """
  The raw count of not purchased items in the warehouse
  """
  inventory: Int
}

type Mutation {
  cart: CartMutations
}

"""
Returns information about a specific purchase
"""
type Order {
  """
  Each order has a unique id which is separate from the user or items they bought
  """
  id: ID!

  """
  The user who made the purchase
  """
  buyer: User!

  """
  A list of all the items they purchased. This is the Variants, not the Products so we know exactly which
  product and which size/color/feature was bought
  """
  items: [Variant!]!

  """
  Calculate the cost to ship all the variants to the users address
  """
  shippingCost: Float
}

"""
A saved payment option for an user
"""
type PaymentMethod {
  id: ID!

  name: String

  description: String

  type: PaymentType!
}

"""
A fix set of payment types that we accept
"""
enum PaymentType {
  CREDIT_CARD

  DEBIT_CARD

  BANK_ACCOUNT
}

"""
A specific product sold by our store. This contains all the high level details but is not the purchasable item.
See Variant for more info.
"""
type Product {
  id: ID!

  """
  Related products for this product, the user can be fetched from the `x-user-id` header
  """
  recommendedProducts: [Product]

  upc: ID!

  title: String

  description: String

  mediaUrl: String

  """
  Mock random date of when a product might be released
  """
  releaseDate: String

  """
  Variants of the products to view specific size/color/price options
  """
  variants(searchInput: VariantSearchInput = {

  }
  ): [Variant]

  reviews: [Review!]
}

"""
Search filters for when returning Products
"""
input ProductSearchInput {
  titleStartsWith: String
}

type Query {
  """
  Get a specific order by id. Meant to be used for a detailed view of an order
  """
  order(id: ID!): Order

  """
  List all available products without any search filters
  """
  listAllProducts: [Product]

  """
  Get all available products to shop for. Optionally provide some search filters
  """
  searchProducts(searchInput: ProductSearchInput! = {

  }
  ): [Product]

  """
  Get all available variants of products to shop for. Optionally provide some search filters
  """
  searchVariants(searchInput: VariantSearchInput! = {

  }
  ): [Variant]

  """
  Get a specific product by id. Useful for the product details page or checkout page
  """
  product(id: ID!): Product

  """
  Get a specific variant by id. Useful for the product details page or checkout page
  """
  variant(id: ID!): Variant

  """
  Get the current user from our fake "auth" headers
  Set the "x-user-id" header to the user id.
  """
  user: User
}

type ResultWithMessage {
  successful: Boolean

  message: String
}

"""
A review of a given product by a specific user
"""
type Review {
  id: ID!

  """
  The plain text version of the review
  """
  body: String

  """
  The person who authored the review
  """
  author: String @deprecated(reason: "Use the new `user` field")

  """
  The User who submitted the review
  """
  user: User

  """
  The product which this review is about
  """
  product: Product
}

"""
An user account in our system
"""
type User {
  id: ID!

  """
  The user's active cart session. Once the cart items have been purchases, they transition to an Order
  """
  cart: Cart

  """
  Suggest products for this user, optionally pass in a specific product id to compare too
  """
  recommendedProducts(productId: ID = null): [Product]

  """
  The users current saved shipping address
  """
  shippingAddress: String

  """
  The users login username
  """
  username: String!

  """
  Get the list of last session id of user activity
  """
  previousSessions: [ID!]

  """
  Total saved loyalty points and rewards
  """
  loyaltyPoints: Int

  """
  Saved payment methods that can be used to submit orders
  """
  paymentMethods: [PaymentMethod]

  """
  The users previous purchases
  """
  orders: [Order]
}

"""
A variant of a product which is a unique combination of attributes like size and color
Variants are the entities that are added to carts and purchased
"""
type Variant {
  id: ID!

  """
  Price in decimals for this variant
  """
  price: Float!

  """
  Checks the warehouse API for inventory information.
  """
  inventory: Inventory

  """
  Link back to the parent Product
  """
  product: Product

  """
  Optional color option for this variant
  """
  colorway: String

  """
  Optional size option for this variant
  """
  size: String

  """
  Optional dimensions. Can be use to calculate other info like shipping or packaging
  """
  dimensions: String

  """
  Optional weight. Can be use to calculate other info like shipping or packaging
  """
  weight: Float
}

"""
Search filters for when returning Variants
"""
input VariantSearchInput {
  sizeStartsWith: String
}

"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip ("Skipped when true." if: Boolean!) on FIELD|FRAGMENT_SPREAD|INLINE_FRAGMENT

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include ("Included when true." if: Boolean!) on FIELD|FRAGMENT_SPREAD|INLINE_FRAGMENT

"""
Marks an element of a GraphQL schema as no longer supported.
"""
directive @deprecated ("Explains why this element was deprecated, usually also including a suggestion for how to access supported similar data. Formatted using the Markdown syntax, as specified by [CommonMark](https:\/\/commonmark.org\/)." reason: String = "No longer supported") on FIELD_DEFINITION|ARGUMENT_DEFINITION|INPUT_FIELD_DEFINITION|ENUM_VALUE

"""
Exposes a URL that specifies the behavior of this scalar.
"""
directive @specifiedBy ("The URL that specifies the behavior of this scalar." url: String!) on SCALAR

directive @defer (label: String, if: Boolean! = true) on FRAGMENT_SPREAD|INLINE_FRAGMENT

schema {
  query: Query
  mutation: Mutation
}
